# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'td_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TapeDriveWindow(object):
    def setupUi(self, TapeDriveWindow):
        TapeDriveWindow.setObjectName("TapeDriveWindow")
        TapeDriveWindow.resize(640, 480)
        TapeDriveWindow.setMinimumSize(QtCore.QSize(640, 480))
        TapeDriveWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        TapeDriveWindow.setStyleSheet("TapeDriveWindow {qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.centralwidget = QtWidgets.QWidget(TapeDriveWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.consoleOut = QtWidgets.QTextBrowser(self.centralwidget)
        self.consoleOut.setGeometry(QtCore.QRect(10, 30, 251, 111))
        self.consoleOut.setObjectName("consoleOut")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 60, 16))
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(270, 10, 301, 131))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btnM1bw = QtWidgets.QPushButton(self.tab)
        self.btnM1bw.setGeometry(QtCore.QRect(80, 30, 71, 41))
        self.btnM1bw.setStyleSheet("QPushButton {background-color: rgba(190,1,25,0.9); border-radius: 5px;}\n"
"\n"
"#be0119")
        self.btnM1bw.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/bw3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnM1bw.setIcon(icon)
        self.btnM1bw.setIconSize(QtCore.QSize(50, 50))
        self.btnM1bw.setObjectName("btnM1bw")
        self.btnM1fw = QtWidgets.QPushButton(self.tab)
        self.btnM1fw.setGeometry(QtCore.QRect(160, 30, 71, 41))
        self.btnM1fw.setStyleSheet("QPushButton {background-color: rgba(190,1,25,0.9); border-radius: 5px;}")
        self.btnM1fw.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Resources/fw3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnM1fw.setIcon(icon1)
        self.btnM1fw.setIconSize(QtCore.QSize(50, 50))
        self.btnM1fw.setObjectName("btnM1fw")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 61, 61))
        self.label_2.setStyleSheet("QLabel {color: white; background-color: #be0119; font: 48px; border: 5px solid #be0119;border-radius:30px; padding-right: 2px; padding-bottom: 2px}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btnM2bw = QtWidgets.QPushButton(self.tab_2)
        self.btnM2bw.setGeometry(QtCore.QRect(80, 30, 71, 41))
        self.btnM2bw.setStyleSheet("QPushButton {background-color: rgba(6,82,255,0.8); border-radius: 5px;}\n"
"#0652ff")
        self.btnM2bw.setText("")
        self.btnM2bw.setIcon(icon)
        self.btnM2bw.setIconSize(QtCore.QSize(50, 50))
        self.btnM2bw.setObjectName("btnM2bw")
        self.btnM2fw = QtWidgets.QPushButton(self.tab_2)
        self.btnM2fw.setGeometry(QtCore.QRect(160, 30, 71, 41))
        self.btnM2fw.setStyleSheet("QPushButton {background-color: rgba(6,82,255,0.8);border-radius: 5px;}")
        self.btnM2fw.setText("")
        self.btnM2fw.setIcon(icon1)
        self.btnM2fw.setIconSize(QtCore.QSize(50, 50))
        self.btnM2fw.setObjectName("btnM2fw")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 61, 61))
        self.label_3.setStyleSheet("QLabel {color: white; background-color: #0652ff; font: 48px; border: 5px solid #0652ff;border-radius:30px; padding-right: 0; padding-bottom: 3px}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.btnForward = QtWidgets.QPushButton(self.centralwidget)
        self.btnForward.setGeometry(QtCore.QRect(350, 250, 151, 91))
        self.btnForward.setStyleSheet("QPushButton {background-color: rgba(0,0,0,0.5); border-radius: 5px;}")
        self.btnForward.setText("")
        self.btnForward.setIcon(icon1)
        self.btnForward.setIconSize(QtCore.QSize(100, 100))
        self.btnForward.setObjectName("btnForward")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 220, 81, 101))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnHome = QtWidgets.QPushButton(self.groupBox)
        self.btnHome.setEnabled(False)
        self.btnHome.setGeometry(QtCore.QRect(10, 30, 61, 61))
        self.btnHome.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Resources/home2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHome.setIcon(icon2)
        self.btnHome.setIconSize(QtCore.QSize(75, 75))
        self.btnHome.setObjectName("btnHome")
        self.homeEnable = QtWidgets.QCheckBox(self.groupBox)
        self.homeEnable.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.homeEnable.setObjectName("homeEnable")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(520, 220, 101, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalSlider = QtWidgets.QSlider(self.groupBox_2)
        self.verticalSlider.setGeometry(QtCore.QRect(10, 30, 21, 160))
        self.verticalSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.verticalSlider.setMinimum(1)
        self.verticalSlider.setMaximum(359)
        self.verticalSlider.setSingleStep(1)
        self.verticalSlider.setPageStep(45)
        self.verticalSlider.setSliderPosition(45)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.verticalSlider.setTickInterval(15)
        self.verticalSlider.setObjectName("verticalSlider")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setGeometry(QtCore.QRect(39, 30, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox.setFont(font)
        self.spinBox.setReadOnly(True)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(359)
        self.spinBox.setProperty("value", 45)
        self.spinBox.setObjectName("spinBox")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(40, 70, 40, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setAcceptDrops(False)
        self.plainTextEdit.setAutoFillBackground(True)
        self.plainTextEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setTabChangesFocus(True)
        self.plainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit.setTabStopWidth(80)
        self.plainTextEdit.setMaximumBlockCount(0)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.btnBackward = QtWidgets.QPushButton(self.centralwidget)
        self.btnBackward.setGeometry(QtCore.QRect(140, 250, 151, 91))
        self.btnBackward.setStyleSheet("QPushButton {background-color: rgba(0,0,0,0.5); border-radius:4px;}")
        self.btnBackward.setText("")
        self.btnBackward.setIcon(icon)
        self.btnBackward.setIconSize(QtCore.QSize(100, 100))
        self.btnBackward.setObjectName("btnBackward")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 621, 51))
        self.label_4.setStyleSheet("QLabel {font-size: 24px; background-color: rgba(0,0,0,0.5); color: white; border-radius: 5px;}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 320, 81, 101))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.btnIsolate = QtWidgets.QPushButton(self.groupBox_3)
        self.btnIsolate.setEnabled(False)
        self.btnIsolate.setGeometry(QtCore.QRect(10, 30, 61, 61))
        self.btnIsolate.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/no-entry.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnIsolate.setIcon(icon3)
        self.btnIsolate.setIconSize(QtCore.QSize(75, 75))
        self.btnIsolate.setObjectName("btnIsolate")
        self.IsolateEnable = QtWidgets.QCheckBox(self.groupBox_3)
        self.IsolateEnable.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.IsolateEnable.setObjectName("IsolateEnable")
        TapeDriveWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TapeDriveWindow)
        self.statusbar.setObjectName("statusbar")
        TapeDriveWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(TapeDriveWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menuBar.setObjectName("menuBar")
        TapeDriveWindow.setMenuBar(self.menuBar)
        self.actionQuit = QtWidgets.QAction(TapeDriveWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNothingHere = QtWidgets.QAction(TapeDriveWindow)
        self.actionNothingHere.setObjectName("actionNothingHere")

        self.retranslateUi(TapeDriveWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TapeDriveWindow)

    def retranslateUi(self, TapeDriveWindow):
        _translate = QtCore.QCoreApplication.translate
        TapeDriveWindow.setWindowTitle(_translate("TapeDriveWindow", "Tape Drive Control"))
        self.label.setText(_translate("TapeDriveWindow", "Log"))
        self.label_2.setText(_translate("TapeDriveWindow", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TapeDriveWindow", "Motor 1"))
        self.label_3.setText(_translate("TapeDriveWindow", "2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("TapeDriveWindow", "Motor 2"))
        self.homeEnable.setText(_translate("TapeDriveWindow", "Enable"))
        self.groupBox_2.setTitle(_translate("TapeDriveWindow", "Step Size (deg)"))
        self.verticalSlider.setToolTip(_translate("TapeDriveWindow", "<html><head/><body><p>Drag to change step size. Step will be set when slider is released.</p></body></html>"))
        self.plainTextEdit.setPlaceholderText(_translate("TapeDriveWindow", "45"))
        self.label_4.setText(_translate("TapeDriveWindow", "Tape Drive Controls"))
        self.IsolateEnable.setText(_translate("TapeDriveWindow", "Enable"))
        self.actionQuit.setText(_translate("TapeDriveWindow", "Exit"))
        self.actionQuit.setShortcut(_translate("TapeDriveWindow", "Meta+Q"))
        self.actionNothingHere.setText(_translate("TapeDriveWindow", "NothingHere"))

import resources_rc
