# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'td_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TapeDriveWindow(object):
    def setupUi(self, TapeDriveWindow):
        TapeDriveWindow.setObjectName("TapeDriveWindow")
        TapeDriveWindow.resize(640, 480)
        TapeDriveWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        TapeDriveWindow.setStyleSheet("TapeDriveWindow {qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.centralwidget = QtWidgets.QWidget(TapeDriveWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.consoleOut = QtWidgets.QTextBrowser(self.centralwidget)
        self.consoleOut.setGeometry(QtCore.QRect(10, 30, 256, 192))
        self.consoleOut.setObjectName("consoleOut")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 60, 16))
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(270, 10, 301, 211))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btnM1bw = QtWidgets.QPushButton(self.tab)
        self.btnM1bw.setGeometry(QtCore.QRect(20, 110, 91, 51))
        self.btnM1bw.setObjectName("btnM1bw")
        self.btnM1fw = QtWidgets.QPushButton(self.tab)
        self.btnM1fw.setGeometry(QtCore.QRect(110, 110, 91, 51))
        self.btnM1fw.setObjectName("btnM1fw")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.btnM2bw = QtWidgets.QPushButton(self.tab_2)
        self.btnM2bw.setGeometry(QtCore.QRect(20, 110, 91, 51))
        self.btnM2bw.setObjectName("btnM2bw")
        self.btnM2fw = QtWidgets.QPushButton(self.tab_2)
        self.btnM2fw.setGeometry(QtCore.QRect(110, 110, 91, 51))
        self.btnM2fw.setObjectName("btnM2fw")
        self.tabWidget.addTab(self.tab_2, "")
        self.btnForward = QtWidgets.QPushButton(self.centralwidget)
        self.btnForward.setGeometry(QtCore.QRect(160, 250, 91, 51))
        self.btnForward.setObjectName("btnForward")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(250, 250, 111, 91))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btnHome = QtWidgets.QPushButton(self.groupBox)
        self.btnHome.setEnabled(False)
        self.btnHome.setGeometry(QtCore.QRect(10, 40, 91, 51))
        self.btnHome.setObjectName("btnHome")
        self.homeEnable = QtWidgets.QCheckBox(self.groupBox)
        self.homeEnable.setGeometry(QtCore.QRect(20, 10, 71, 20))
        self.homeEnable.setObjectName("homeEnable")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 220, 101, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalSlider = QtWidgets.QSlider(self.groupBox_2)
        self.verticalSlider.setGeometry(QtCore.QRect(10, 30, 21, 160))
        self.verticalSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.verticalSlider.setMinimum(1)
        self.verticalSlider.setMaximum(359)
        self.verticalSlider.setSingleStep(1)
        self.verticalSlider.setPageStep(45)
        self.verticalSlider.setSliderPosition(45)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.verticalSlider.setTickInterval(15)
        self.verticalSlider.setObjectName("verticalSlider")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setGeometry(QtCore.QRect(40, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox.setFont(font)
        self.spinBox.setReadOnly(True)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(359)
        self.spinBox.setProperty("value", 45)
        self.spinBox.setObjectName("spinBox")
        self.btnBackward = QtWidgets.QPushButton(self.centralwidget)
        self.btnBackward.setGeometry(QtCore.QRect(70, 250, 91, 51))
        self.btnBackward.setObjectName("btnBackward")
        TapeDriveWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TapeDriveWindow)
        self.statusbar.setObjectName("statusbar")
        TapeDriveWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(TapeDriveWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuNone = QtWidgets.QMenu(self.menuBar)
        self.menuNone.setObjectName("menuNone")
        self.menuNotAMenu = QtWidgets.QMenu(self.menuBar)
        self.menuNotAMenu.setObjectName("menuNotAMenu")
        TapeDriveWindow.setMenuBar(self.menuBar)
        self.actionQuit = QtWidgets.QAction(TapeDriveWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNothingHere = QtWidgets.QAction(TapeDriveWindow)
        self.actionNothingHere.setObjectName("actionNothingHere")
        self.menuNone.addAction(self.actionQuit)
        self.menuNotAMenu.addAction(self.actionNothingHere)
        self.menuBar.addAction(self.menuNotAMenu.menuAction())
        self.menuBar.addAction(self.menuNone.menuAction())

        self.retranslateUi(TapeDriveWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TapeDriveWindow)

    def retranslateUi(self, TapeDriveWindow):
        _translate = QtCore.QCoreApplication.translate
        TapeDriveWindow.setWindowTitle(_translate("TapeDriveWindow", "Tape Drive Control"))
        self.label.setText(_translate("TapeDriveWindow", "Log"))
        self.btnM1bw.setText(_translate("TapeDriveWindow", "Backward"))
        self.btnM1fw.setText(_translate("TapeDriveWindow", "Forward"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TapeDriveWindow", "Motor 1"))
        self.btnM2bw.setText(_translate("TapeDriveWindow", "Backward"))
        self.btnM2fw.setText(_translate("TapeDriveWindow", "Forward"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("TapeDriveWindow", "Motor 2"))
        self.btnForward.setText(_translate("TapeDriveWindow", "Forward"))
        self.btnHome.setText(_translate("TapeDriveWindow", "Home"))
        self.homeEnable.setText(_translate("TapeDriveWindow", "Enable"))
        self.groupBox_2.setTitle(_translate("TapeDriveWindow", "Step Size (deg)"))
        self.verticalSlider.setToolTip(_translate("TapeDriveWindow", "<html><head/><body><p>Drag to change step size. Step will be when slider is released.</p></body></html>"))
        self.btnBackward.setText(_translate("TapeDriveWindow", "Backward"))
        self.menuNone.setTitle(_translate("TapeDriveWindow", "TapeDriveUI"))
        self.menuNotAMenu.setTitle(_translate("TapeDriveWindow", "NotAMenu"))
        self.actionQuit.setText(_translate("TapeDriveWindow", "Exit"))
        self.actionQuit.setShortcut(_translate("TapeDriveWindow", "Meta+Q"))
        self.actionNothingHere.setText(_translate("TapeDriveWindow", "NothingHere"))

